esphome:
  name: rh-sdm72dm-v2-inverter
  friendly_name: Riehlhome SDM72DM-V2 (Inverter)
  name_add_mac_suffix: true

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

logger:
api:
ota:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

uart:
  id: uart_a
  tx_pin: 04
  rx_pin: 36
  baud_rate: 19200
  data_bits: 8
  stop_bits: 1

modbus:
  send_wait_time: 10ms
  id: modbus_a

modbus_controller:
  - id: modbus_controller_a
    modbus_id: modbus_a
    address: 0x02
    update_interval: 3s

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "l1_power"
    name: "L1 Power"
    address: 0x000C
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "l2_power"
    name: "L2 Power"
    address: 0x000E
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "l3_power"
    name: "L3 Power"
    address: 0x0010
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "import_energy"
    name: "Import Energy"
    address: 0x0048
    register_type: read
    value_type: FP32
    device_class: "energy"
    state_class: "total"
    unit_of_measurement: "kWh"
    skip_updates: 60
    accuracy_decimals: 2
